### ISSUE TITLE
Develop UI

### ISSUE THREAD

**Issue by unpadforstrays** [unpadforstrays/unpadforstrays.or.id#2]
Using Bento UI approach and Google Text Font

- [x] Figma Jam session
- [x] Finalize

Figma link: [Link](https://www.figma.com/file/9KkXwYvqzuBlWLZO3i7zwk/landing-page?type=design&node-id=0-1&mode=design)

**Comment by kodekatz** [comment]
Figma untuk page about, page contact, page blog index, page blog, sama page volunteering?

**Comment by unpadforstrays** [comment]
cek Figma makanya :((
